### ISSUE TITLE
Was this repository forked from mine?

### ISSUE THREAD

**Issue by yzy1996** [weihaox/arxiv_daily_tools#1]
Hope to be mentioned. [related code](https://github.com/yzy1996/Python-Code/tree/master/Python%2BarXiv)

**Comment by weihaox** [comment]
Thank you for sharing! I recall that it was possibly adapted from your repo, but I was unable to locate the repository at the time of writing README. It seems that the original repo has since been relocated and merged to another one. See the updated information 822c9199e2509ede65b53a4c423c50a870a54980.

**Comment by yzy1996** [comment]
Glad to see that it helps you.
